# Generated by Django 4.2.10 on 2024-03-02 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forums.forumpost'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
